### ISSUE TITLE
Question regarding the json data set

### ISSUE THREAD

**Issue by mailmann006** [efekarakus/mozaic#1]
Could you tell me how you created the example data set? I understand how the information is stored in the json file, but I am at a loss at how to generate a data set automatically from my own images. I have tried to write a script in js but haven't had much luck. What i'm looking to do is have users upload images to a public folder, then after so many images have been uploaded or based on time I will display a mosaic on the site. I'm pretty sure I could do it in python but I would love to create the data set on a server, on the fly.

**Comment by efekarakus** [comment]
Hello,

so it's been a really long time since I've looked at this project. But based on the json data file that I have https://raw.githubusercontent.com/efekarakus/mozaic/master/examples/tiles/all-tiles.json, it looks like the json input file needs to be formatted as:

{
    "width": pixel width of one tile,
    "height": pixel height of one tile,
     "data":  [ [tile1], [tile2], ..., [tileN] ]
}

Where each tileJ in data is of the format = [[r1, g1, b1], [r2, g2, b3], ...] for every pixel in the tile.
To be honest, this project was done when I was a sophomore in college so the input dataset doesn't make much sense :/ but hopefully this helped.

**Comment by mailmann006** [comment]
I see, you just need to enumerate through the 20 x 20 tile pixel by pixel in RGB for the data set. Neat! Hey, I could handle that on the Commodore64 ;) Thanks for clearing that up.
